const initialProjects = [
  {
    title: "Desk",
    slug: "desk",
    image: "https://unsplash.com/de/fotos/brauner-holztisch-nME9TubZtSo",
    description:
      "A wooden desk that can be used as dinner table or working desk.",
    duration: "short",
    cost: "$$",
    difficulty: "easy",
    material: [
      { amount: 1, material: "wooden plate" },
      { amount: 4, material: "legs" },
      { amount: 50, material: "screws" },
      { amount: 4, material: "angles" },
      { amount: 1, material: "wood oil" },
    ],
    instructions: [
      "Apply oil to the wooden plate, allow to soak in and remove excess material after 15 minutes. Polish over with a textile cloth and oil again.",
      "Turn the wooden plate and put it on the floor.",
      "Put each angle to one of the corners and use a screwdriver to fixate them with some screws.",
      "Put one leg to each corner where the angles are already fixated and screw the legs on the angles.",
      "Turn the table and use as you like :)",
    ],
  },
  {
    title: "Cedar Live Edge Coffee Table",
    slug: "coffee_table",
    image:
      "https://i.pinimg.com/564x/71/bb/ad/71bbadf88f9cf53eeb70fb63f73b9d37.jpg",
    description: "A small Wooden Table for the Living room area.",
    duration: "short",
    cost: "$",
    difficulty: "easy",
    material: [
      { amount: 1, material: "wooden disk" },
      { amount: 4, material: "hairpin legs" },
      { amount: 16, material: "Screws 3,5x25mm" },
      { amount: 1, material: "sandpaper" },
      { amount: 1, material: "wood oil" },
    ],
    instructions: [
      "Sand the Wooden Disc until you have a smooth surface.",
      "Clean the surface from dust and use 2 coats of Wood Oil.",
      "Position the Metal legs under the Disc and screw it in position.",
    ],
  },
  {
    title: "Floating Bookshelves",
    slug: "floating_bookshelves",
    image:
      "https://images.unsplash.com/photo-1567083348161-9dfccc0d47d9?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZmxvYXRpbmclMjBzaGVsZnxlbnwwfHwwfHx8MA%3D%3D",
    description: "Create stylish and space-saving floating bookshelves.",
    duration: "short",
    cost: "$",
    difficulty: "medium",
    material: [
      { amount: 4, material: "wooden boards" },
      { amount: 8, material: "L-shaped brackets" },
      { amount: 1, material: "Screwdriver" },
    ],
    instructions: [
      "Measure and mark desired locations for your shelves on the wall.",
      "Install L-shaped brackets at the marked spots using screws.",
      "Attach wooden boards to the brackets securely, formatting the floating shelves.",
      "Paint  or finish the shelves to match your room’s decor.",
      "Let the shelves dry.",
    ],
  },
  {
    title: "Dream Catcher",
    slug: "dream_catcher",
    image:
      "https://unsplash.com/photos/a-dream-catcher-hanging-from-a-rope-with-tassels-oH3HtzxPXm4",
    description: "dream catcher hanging from a rope with tassels",
    duration: "short",
    cost: "$",
    difficulty: "medium",
    material: [
      { amount: 1, material: "metal ring" },
      { amount: 1, material: "white yarn" },
      { amount: 1, material: "earthy orange yarn" },
      { amount: 1, material: "blue yarn" },
      { amount: 1, material: "leather band or hanf" },
      { amount: 1, material: "scissor" },
    ],
    instructions: [
      "Start to wrap the beige leather band around the ring. Leave a few centimeters free at the beginning so that you can make the hanger for your dream catcher later.",
      "Continue to wrap leather strap around the metal ring and when there is no more metal visible, knot the two ends.",
      "Now weave the net: Tie the end of the yarn exactly around the base of the knotted leather strap and wrap it once around the ring. Pull the yarn and knot it around the ring again to create a loop. Repeat this step several times and when you reach the end, pull the yarn through the first and second loop to create a new loop. When the opening in the middle becomes small enough, simply knot the thread to close the net.",
      "Cut out three strips of yarn.",
      "Thread blue beads onto each strip and attach a feather to the end.",
      "Tie the strips of yarn around the dream catcher.",
    ],
  },
];
